/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShoplistRouteImport } from './routes/shoplist'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as CraftRouteImport } from './routes/craft'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CraftIndexRouteImport } from './routes/craft.index'
import { Route as CraftItemIdRouteImport } from './routes/craft.$itemId'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'

const ShoplistRoute = ShoplistRouteImport.update({
  id: '/shoplist',
  path: '/shoplist',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CraftRoute = CraftRouteImport.update({
  id: '/craft',
  path: '/craft',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CraftIndexRoute = CraftIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CraftRoute,
} as any)
const CraftItemIdRoute = CraftItemIdRouteImport.update({
  id: '/$itemId',
  path: '/$itemId',
  getParentRoute: () => CraftRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/craft': typeof CraftRouteWithChildren
  '/profile': typeof ProfileRoute
  '/shoplist': typeof ShoplistRoute
  '/craft/$itemId': typeof CraftItemIdRoute
  '/craft/': typeof CraftIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/shoplist': typeof ShoplistRoute
  '/craft/$itemId': typeof CraftItemIdRoute
  '/craft': typeof CraftIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/craft': typeof CraftRouteWithChildren
  '/profile': typeof ProfileRoute
  '/shoplist': typeof ShoplistRoute
  '/craft/$itemId': typeof CraftItemIdRoute
  '/craft/': typeof CraftIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/craft'
    | '/profile'
    | '/shoplist'
    | '/craft/$itemId'
    | '/craft/'
    | '/api/auth/$'
    | '/api/trpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile'
    | '/shoplist'
    | '/craft/$itemId'
    | '/craft'
    | '/api/auth/$'
    | '/api/trpc/$'
  id:
    | '__root__'
    | '/'
    | '/craft'
    | '/profile'
    | '/shoplist'
    | '/craft/$itemId'
    | '/craft/'
    | '/api/auth/$'
    | '/api/trpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CraftRoute: typeof CraftRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  ShoplistRoute: typeof ShoplistRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shoplist': {
      id: '/shoplist'
      path: '/shoplist'
      fullPath: '/shoplist'
      preLoaderRoute: typeof ShoplistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/craft': {
      id: '/craft'
      path: '/craft'
      fullPath: '/craft'
      preLoaderRoute: typeof CraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/craft/': {
      id: '/craft/'
      path: '/'
      fullPath: '/craft/'
      preLoaderRoute: typeof CraftIndexRouteImport
      parentRoute: typeof CraftRoute
    }
    '/craft/$itemId': {
      id: '/craft/$itemId'
      path: '/$itemId'
      fullPath: '/craft/$itemId'
      preLoaderRoute: typeof CraftItemIdRouteImport
      parentRoute: typeof CraftRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CraftRouteChildren {
  CraftItemIdRoute: typeof CraftItemIdRoute
  CraftIndexRoute: typeof CraftIndexRoute
}

const CraftRouteChildren: CraftRouteChildren = {
  CraftItemIdRoute: CraftItemIdRoute,
  CraftIndexRoute: CraftIndexRoute,
}

const CraftRouteWithChildren = CraftRoute._addFileChildren(CraftRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CraftRoute: CraftRouteWithChildren,
  ProfileRoute: ProfileRoute,
  ShoplistRoute: ShoplistRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
