/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as ShoplistsRouteImport } from './routes/shoplists'
import { Route as ShoplistRouteImport } from './routes/shoplist'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ItemRouteImport } from './routes/item'
import { Route as CraftRouteImport } from './routes/craft'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SimulatorIndexRouteImport } from './routes/simulator.index'
import { Route as ShoplistsCombineRouteImport } from './routes/shoplists.combine'
import { Route as ShoplistsIndexRouteImport } from './routes/shoplists.index'
import { Route as ItemIndexRouteImport } from './routes/item.index'
import { Route as CraftIndexRouteImport } from './routes/craft.index'
import { Route as SimulatorItemIdRouteImport } from './routes/simulator.$itemId'
import { Route as ShoplistsListIdRouteImport } from './routes/shoplists.$listId'
import { Route as ItemItemIdRouteImport } from './routes/item.$itemId'
import { Route as CraftItemIdRouteImport } from './routes/craft.$itemId'
import { Route as ShoplistsInviteTokenRouteImport } from './routes/shoplists.invite.$token'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc.$'
import { Route as ApiStaticItemsAllRouteImport } from './routes/api/static/items-all'
import { Route as ApiStaticCraftsAllRouteImport } from './routes/api/static/crafts-all'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'

const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoplistsRoute = ShoplistsRouteImport.update({
  id: '/shoplists',
  path: '/shoplists',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoplistRoute = ShoplistRouteImport.update({
  id: '/shoplist',
  path: '/shoplist',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemRoute = ItemRouteImport.update({
  id: '/item',
  path: '/item',
  getParentRoute: () => rootRouteImport,
} as any)
const CraftRoute = CraftRouteImport.update({
  id: '/craft',
  path: '/craft',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorIndexRoute = SimulatorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SimulatorRoute,
} as any)
const ShoplistsIndexRoute = ShoplistsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShoplistsRoute,
} as any)
const ShoplistsCombineRoute = ShoplistsCombineRouteImport.update({
  id: '/combine',
  path: '/combine',
  getParentRoute: () => ShoplistsRoute,
} as any)
const ItemIndexRoute = ItemIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ItemRoute,
} as any)
const CraftIndexRoute = CraftIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CraftRoute,
} as any)
const SimulatorItemIdRoute = SimulatorItemIdRouteImport.update({
  id: '/$itemId',
  path: '/$itemId',
  getParentRoute: () => SimulatorRoute,
} as any)
const ShoplistsListIdRoute = ShoplistsListIdRouteImport.update({
  id: '/$listId',
  path: '/$listId',
  getParentRoute: () => ShoplistsRoute,
} as any)
const ItemItemIdRoute = ItemItemIdRouteImport.update({
  id: '/$itemId',
  path: '/$itemId',
  getParentRoute: () => ItemRoute,
} as any)
const CraftItemIdRoute = CraftItemIdRouteImport.update({
  id: '/$itemId',
  path: '/$itemId',
  getParentRoute: () => CraftRoute,
} as any)
const ShoplistsInviteTokenRoute = ShoplistsInviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => ShoplistsRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStaticItemsAllRoute = ApiStaticItemsAllRouteImport.update({
  id: '/api/static/items-all',
  path: '/api/static/items-all',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStaticCraftsAllRoute = ApiStaticCraftsAllRouteImport.update({
  id: '/api/static/crafts-all',
  path: '/api/static/crafts-all',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/craft': typeof CraftRouteWithChildren
  '/item': typeof ItemRouteWithChildren
  '/profile': typeof ProfileRoute
  '/shoplist': typeof ShoplistRoute
  '/shoplists': typeof ShoplistsRouteWithChildren
  '/simulator': typeof SimulatorRouteWithChildren
  '/craft/$itemId': typeof CraftItemIdRoute
  '/item/$itemId': typeof ItemItemIdRoute
  '/shoplists/$listId': typeof ShoplistsListIdRoute
  '/simulator/$itemId': typeof SimulatorItemIdRoute
  '/craft/': typeof CraftIndexRoute
  '/item/': typeof ItemIndexRoute
  '/shoplists/combine': typeof ShoplistsCombineRoute
  '/shoplists/': typeof ShoplistsIndexRoute
  '/simulator/': typeof SimulatorIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/static/crafts-all': typeof ApiStaticCraftsAllRoute
  '/api/static/items-all': typeof ApiStaticItemsAllRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/shoplists/invite/$token': typeof ShoplistsInviteTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/shoplist': typeof ShoplistRoute
  '/craft/$itemId': typeof CraftItemIdRoute
  '/item/$itemId': typeof ItemItemIdRoute
  '/shoplists/$listId': typeof ShoplistsListIdRoute
  '/shoplists/combine': typeof ShoplistsCombineRoute
  '/simulator/$itemId': typeof SimulatorItemIdRoute
  '/craft': typeof CraftIndexRoute
  '/item': typeof ItemIndexRoute
  '/shoplists': typeof ShoplistsIndexRoute
  '/simulator': typeof SimulatorIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/static/crafts-all': typeof ApiStaticCraftsAllRoute
  '/api/static/items-all': typeof ApiStaticItemsAllRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/shoplists/invite/$token': typeof ShoplistsInviteTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/craft': typeof CraftRouteWithChildren
  '/item': typeof ItemRouteWithChildren
  '/profile': typeof ProfileRoute
  '/shoplist': typeof ShoplistRoute
  '/shoplists': typeof ShoplistsRouteWithChildren
  '/simulator': typeof SimulatorRouteWithChildren
  '/craft/$itemId': typeof CraftItemIdRoute
  '/item/$itemId': typeof ItemItemIdRoute
  '/shoplists/$listId': typeof ShoplistsListIdRoute
  '/simulator/$itemId': typeof SimulatorItemIdRoute
  '/craft/': typeof CraftIndexRoute
  '/item/': typeof ItemIndexRoute
  '/shoplists/combine': typeof ShoplistsCombineRoute
  '/shoplists/': typeof ShoplistsIndexRoute
  '/simulator/': typeof SimulatorIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/static/crafts-all': typeof ApiStaticCraftsAllRoute
  '/api/static/items-all': typeof ApiStaticItemsAllRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/shoplists/invite/$token': typeof ShoplistsInviteTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/craft'
    | '/item'
    | '/profile'
    | '/shoplist'
    | '/shoplists'
    | '/simulator'
    | '/craft/$itemId'
    | '/item/$itemId'
    | '/shoplists/$listId'
    | '/simulator/$itemId'
    | '/craft/'
    | '/item/'
    | '/shoplists/combine'
    | '/shoplists/'
    | '/simulator/'
    | '/api/auth/$'
    | '/api/static/crafts-all'
    | '/api/static/items-all'
    | '/api/trpc/$'
    | '/shoplists/invite/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile'
    | '/shoplist'
    | '/craft/$itemId'
    | '/item/$itemId'
    | '/shoplists/$listId'
    | '/shoplists/combine'
    | '/simulator/$itemId'
    | '/craft'
    | '/item'
    | '/shoplists'
    | '/simulator'
    | '/api/auth/$'
    | '/api/static/crafts-all'
    | '/api/static/items-all'
    | '/api/trpc/$'
    | '/shoplists/invite/$token'
  id:
    | '__root__'
    | '/'
    | '/craft'
    | '/item'
    | '/profile'
    | '/shoplist'
    | '/shoplists'
    | '/simulator'
    | '/craft/$itemId'
    | '/item/$itemId'
    | '/shoplists/$listId'
    | '/simulator/$itemId'
    | '/craft/'
    | '/item/'
    | '/shoplists/combine'
    | '/shoplists/'
    | '/simulator/'
    | '/api/auth/$'
    | '/api/static/crafts-all'
    | '/api/static/items-all'
    | '/api/trpc/$'
    | '/shoplists/invite/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CraftRoute: typeof CraftRouteWithChildren
  ItemRoute: typeof ItemRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  ShoplistRoute: typeof ShoplistRoute
  ShoplistsRoute: typeof ShoplistsRouteWithChildren
  SimulatorRoute: typeof SimulatorRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiStaticCraftsAllRoute: typeof ApiStaticCraftsAllRoute
  ApiStaticItemsAllRoute: typeof ApiStaticItemsAllRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shoplists': {
      id: '/shoplists'
      path: '/shoplists'
      fullPath: '/shoplists'
      preLoaderRoute: typeof ShoplistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shoplist': {
      id: '/shoplist'
      path: '/shoplist'
      fullPath: '/shoplist'
      preLoaderRoute: typeof ShoplistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/item': {
      id: '/item'
      path: '/item'
      fullPath: '/item'
      preLoaderRoute: typeof ItemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/craft': {
      id: '/craft'
      path: '/craft'
      fullPath: '/craft'
      preLoaderRoute: typeof CraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator/': {
      id: '/simulator/'
      path: '/'
      fullPath: '/simulator/'
      preLoaderRoute: typeof SimulatorIndexRouteImport
      parentRoute: typeof SimulatorRoute
    }
    '/shoplists/': {
      id: '/shoplists/'
      path: '/'
      fullPath: '/shoplists/'
      preLoaderRoute: typeof ShoplistsIndexRouteImport
      parentRoute: typeof ShoplistsRoute
    }
    '/shoplists/combine': {
      id: '/shoplists/combine'
      path: '/combine'
      fullPath: '/shoplists/combine'
      preLoaderRoute: typeof ShoplistsCombineRouteImport
      parentRoute: typeof ShoplistsRoute
    }
    '/item/': {
      id: '/item/'
      path: '/'
      fullPath: '/item/'
      preLoaderRoute: typeof ItemIndexRouteImport
      parentRoute: typeof ItemRoute
    }
    '/craft/': {
      id: '/craft/'
      path: '/'
      fullPath: '/craft/'
      preLoaderRoute: typeof CraftIndexRouteImport
      parentRoute: typeof CraftRoute
    }
    '/simulator/$itemId': {
      id: '/simulator/$itemId'
      path: '/$itemId'
      fullPath: '/simulator/$itemId'
      preLoaderRoute: typeof SimulatorItemIdRouteImport
      parentRoute: typeof SimulatorRoute
    }
    '/shoplists/$listId': {
      id: '/shoplists/$listId'
      path: '/$listId'
      fullPath: '/shoplists/$listId'
      preLoaderRoute: typeof ShoplistsListIdRouteImport
      parentRoute: typeof ShoplistsRoute
    }
    '/item/$itemId': {
      id: '/item/$itemId'
      path: '/$itemId'
      fullPath: '/item/$itemId'
      preLoaderRoute: typeof ItemItemIdRouteImport
      parentRoute: typeof ItemRoute
    }
    '/craft/$itemId': {
      id: '/craft/$itemId'
      path: '/$itemId'
      fullPath: '/craft/$itemId'
      preLoaderRoute: typeof CraftItemIdRouteImport
      parentRoute: typeof CraftRoute
    }
    '/shoplists/invite/$token': {
      id: '/shoplists/invite/$token'
      path: '/invite/$token'
      fullPath: '/shoplists/invite/$token'
      preLoaderRoute: typeof ShoplistsInviteTokenRouteImport
      parentRoute: typeof ShoplistsRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/static/items-all': {
      id: '/api/static/items-all'
      path: '/api/static/items-all'
      fullPath: '/api/static/items-all'
      preLoaderRoute: typeof ApiStaticItemsAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/static/crafts-all': {
      id: '/api/static/crafts-all'
      path: '/api/static/crafts-all'
      fullPath: '/api/static/crafts-all'
      preLoaderRoute: typeof ApiStaticCraftsAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CraftRouteChildren {
  CraftItemIdRoute: typeof CraftItemIdRoute
  CraftIndexRoute: typeof CraftIndexRoute
}

const CraftRouteChildren: CraftRouteChildren = {
  CraftItemIdRoute: CraftItemIdRoute,
  CraftIndexRoute: CraftIndexRoute,
}

const CraftRouteWithChildren = CraftRoute._addFileChildren(CraftRouteChildren)

interface ItemRouteChildren {
  ItemItemIdRoute: typeof ItemItemIdRoute
  ItemIndexRoute: typeof ItemIndexRoute
}

const ItemRouteChildren: ItemRouteChildren = {
  ItemItemIdRoute: ItemItemIdRoute,
  ItemIndexRoute: ItemIndexRoute,
}

const ItemRouteWithChildren = ItemRoute._addFileChildren(ItemRouteChildren)

interface ShoplistsRouteChildren {
  ShoplistsCombineRoute: typeof ShoplistsCombineRoute
  ShoplistsListIdRoute: typeof ShoplistsListIdRoute
  ShoplistsIndexRoute: typeof ShoplistsIndexRoute
  ShoplistsInviteTokenRoute: typeof ShoplistsInviteTokenRoute
}

const ShoplistsRouteChildren: ShoplistsRouteChildren = {
  ShoplistsCombineRoute: ShoplistsCombineRoute,
  ShoplistsListIdRoute: ShoplistsListIdRoute,
  ShoplistsIndexRoute: ShoplistsIndexRoute,
  ShoplistsInviteTokenRoute: ShoplistsInviteTokenRoute,
}

const ShoplistsRouteWithChildren = ShoplistsRoute._addFileChildren(
  ShoplistsRouteChildren,
)

interface SimulatorRouteChildren {
  SimulatorItemIdRoute: typeof SimulatorItemIdRoute
  SimulatorIndexRoute: typeof SimulatorIndexRoute
}

const SimulatorRouteChildren: SimulatorRouteChildren = {
  SimulatorItemIdRoute: SimulatorItemIdRoute,
  SimulatorIndexRoute: SimulatorIndexRoute,
}

const SimulatorRouteWithChildren = SimulatorRoute._addFileChildren(
  SimulatorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CraftRoute: CraftRouteWithChildren,
  ItemRoute: ItemRouteWithChildren,
  ProfileRoute: ProfileRoute,
  ShoplistRoute: ShoplistRoute,
  ShoplistsRoute: ShoplistsRouteWithChildren,
  SimulatorRoute: SimulatorRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiStaticCraftsAllRoute: ApiStaticCraftsAllRoute,
  ApiStaticItemsAllRoute: ApiStaticItemsAllRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
